ERROR - 2022-08-28 22:19:05 --> Error connecting to the database: php_network_getaddresses: getaddrinfo for **** failed: No such host is known. 
CRITICAL - 2022-08-28 22:19:05 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for **** failed: No such host is known. 
#0 D:\xampp\htdocs\investment\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\investment\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\investment\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\investment\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\investment\app\Controllers\Auth\Auth.php(85): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\investment\system\CodeIgniter.php(832): App\Controllers\Auth\Auth->auth()
#6 D:\xampp\htdocs\investment\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Auth))
#7 D:\xampp\htdocs\investment\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\investment\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-08-28 22:23:10 --> Error connecting to the database: php_network_getaddresses: getaddrinfo for **** failed: No such host is known. 
CRITICAL - 2022-08-28 22:23:10 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for **** failed: No such host is known. 
#0 D:\xampp\htdocs\investment\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\investment\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\investment\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\investment\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\investment\app\Controllers\Auth\Auth.php(85): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\investment\system\CodeIgniter.php(832): App\Controllers\Auth\Auth->auth()
#6 D:\xampp\htdocs\investment\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Auth))
#7 D:\xampp\htdocs\investment\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\investment\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-08-28 22:23:18 --> Error connecting to the database: php_network_getaddresses: getaddrinfo for **** failed: No such host is known. 
CRITICAL - 2022-08-28 22:23:18 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for **** failed: No such host is known. 
#0 D:\xampp\htdocs\investment\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\investment\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\xampp\htdocs\investment\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\investment\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 D:\xampp\htdocs\investment\app\Controllers\Auth\Auth.php(85): CodeIgniter\BaseModel->first()
#5 D:\xampp\htdocs\investment\system\CodeIgniter.php(832): App\Controllers\Auth\Auth->auth()
#6 D:\xampp\htdocs\investment\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Auth))
#7 D:\xampp\htdocs\investment\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\investment\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
